# DEFAULT
default-init:
  dialect: postgres
  datasource: user=postgres dbname=postgres sslmode=disable
  dir: db/init
  table: emobi_service_init

default-factories:
  dialect: postgres
  datasource: user=postgres dbname=postgres sslmode=disable search_path=emobi_service
  dir: db/factories
  table: factories

default-migrations:
  dialect: postgres
  datasource: user=postgres dbname=postgres sslmode=disable search_path=emobi_service
  dir: db/migrations
  table: migrations

default-seeds:
  dialect: postgres
  datasource: user=postgres dbname=postgres sslmode=disable search_path=emobi_service
  dir: db/seeds
  table: seeds